In [2]:
# Dataset Overview
# The Iris flower data set or Fisher's Iris data set is a multivariate data set introduced by 
# Sir Ronald Fisher in the 1936 as an example of discriminant analysis.
# The data set consists of 50 samples from each of three species of Iris
# (Iris setosa, Iris virginica and Iris versicolor), so 150 total samples. 
# Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

In [5]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

dataset = sns.load_dataset('iris')
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [15]:
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

from sklearn.metrics import classification_report,confusion_matrix
cm = confusion_matrix(y_test,y_pred)
report = classification_report(y_test,y_pred)
print(cm)
print('-----------------------------------------------------------------------')
print(report)

[[ 8  0  0]
 [ 0 20  0]
 [ 0  0 17]]
-----------------------------------------------------------------------
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00         8
 versicolor       1.00      1.00      1.00        20
  virginica       1.00      1.00      1.00        17

avg / total       1.00      1.00      1.00        45



In [19]:
from sklearn.grid_search import GridSearchCV
param_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}
grid = GridSearchCV(SVC(),param_grid,verbose=3)
grid.fit(X_train,y_train)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ......................... C=0.1, gamma=1, score=0.942857 -   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ......................... C=0.1, gamma=1, score=0.971429 -   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ......................... C=0.1, gamma=1, score=0.914286 -   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....................... C=0.1, gamma=0.1, score=0.714286 -   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....................... C=0.1, gamma=0.1, score=0.714286 -   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ....................... C=0.1, gamma=0.1, score=0.800000 -   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ...........

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ................... C=1000, gamma=0.0001, score=0.971429 -   0.0s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................... C=1000, gamma=0.0001, score=0.971429 -   0.0s
[CV] C=1000, gamma=0.0001 ............................................
[CV] ................... C=1000, gamma=0.0001, score=0.971429 -   0.0s


[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:    0.1s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=3)

In [24]:
grid.best_params_

{'C': 10, 'gamma': 0.01}

In [27]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))
print('-------------------------------------------------------------------------------')
print(classification_report(y_test,grid_predictions))

[[ 8  0  0]
 [ 0 20  0]
 [ 0  0 17]]
-------------------------------------------------------------------------------
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00         8
 versicolor       1.00      1.00      1.00        20
  virginica       1.00      1.00      1.00        17

avg / total       1.00      1.00      1.00        45

